name: 'Generate GitBlog README'
on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: 'recursive'
      - run: git submodule update --remote
      - name: Generate README
        uses: ./.github/actions/gitlog
